### ISSUE TITLE
Incorrect parameter passing in subprocess.call

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/vfatqc-python-scripts#305]
## Brief summary of issue

When running the `sbitThresh` scan through `run_scans.py` for GE21 detector, the printed command looks ok, however the scan doesn't run although the wrapper reports correct execution.
The error is not caught by the wrapper script, so the user is not notified that the code crashed.
When executing the printed command manually, scan is performing just fine.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

The scan should perform properly through the wrapper. Any issues encountered during the scan should be reported to the user and not be hidden in the log file.
## Current Behavior

Scan silently fails. 
### Steps to Reproduce (for bugs)

Run a scan on GE21 system, i.e.:
```bash
run_scans.py --gemType ge21 --detType m4 sbitThresh 2 7 0x8
16 Apr 2020 16:23:34.794 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: mkdir -p /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//2020.04.16.16.23
16 Apr 2020 16:23:37.848 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: chmod g+rw /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//2020.04.16.16.23
16 Apr 2020 16:23:37.855 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: unlink /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//current
16 Apr 2020 16:23:37.859 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: ln -s 2020.04.16.16.23 /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//current
16 Apr 2020 16:23:37.865 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: sbitThreshScan.py --gemType ge21 --detType m4 -f /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//2020.04.16.16.23/SBitRateData.root --scanmax=255 --scanmin=0 --stepSize=1 --waitTime=1 2 7 0x8
16 Apr 2020 16:23:37.944 [7fee090dc740] INFO - wrappers::runCommand <> - Executing command: chmod -R g+rw /data/bigdisk/GEM-Data-Taking/GE21_Integration//sbitRate/channelOR//2020.04.16.16.23
Finished all SBIT Rate vs. CFG_THR_ARM_DAC scans for all optohybrids on shelf2 slot7 in ohMask: 0x8
bye
```
Log file content:
```python
usage: sbitThreshScan.py [-h] [--chMin CHMIN] [--chMax CHMAX] [-d]
                         [-f FILENAME] [--perchannel] [--scanmin SCANMIN]
                         [--scanmax SCANMAX] [--stepSize STEPSIZE]
                         [--waitTime WAITTIME] [--gemType GEMTYPE]
                         [--detType DETTYPE]
                         shelf slot ohMask
sbitThreshScan.py: error: argument shelf: invalid int value: '--gemType ge21'
```

## Your Environment

* Version used: gempython_vfatqc-2.8.0-1.1f11c73git.centos7.python2.7.noarch
* Shell used:

**Comment by lpetre-ulb** [comment]
I think there are two issues here. The first one is that the wrapper script silently fails. That is a long standing issue, known by all regular users. Is it worth being fixed in the legacy software?

The second issue is the bug in itself. In this case, it comes from the `run_scans.py` script itself which doesn't packed the arguments properly. Indeed, there are missing `=` sign between the argument and its value (true for other scans as well) :

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/1f11c736de630deba24c7da927eeb9746206db93/run_scans.py#L327-L328

While the format with the equal sign works fine from the command line, the fact that `--gemType {}` is passed as _one_ argument makes the difference when called from `subprocess.call`.
